buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'de.siegmar:fastcsv:2.2.2'
    }
}

plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true

    runs {
        configureEach {
            jvmArgs '-Xmx1024M', '-Xms256M', '-XX:+UseG1GC'
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            workingDirectory project.file('run')
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        client2 {
            parent runs.client
            workingDirectory project.file('run2')
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--username', 'Victim_Test'
        }

        client3 {
            parent runs.client
            workingDirectory project.file('run3')
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--username', 'Victim_Test2'
        }

        client4 {
            parent runs.client
            workingDirectory project.file('run4')
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--username', 'Victim_Test3'
        }

        client5 {
            parent runs.client
            workingDirectory project.file('run5')
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--username', 'Victim_Test4'
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            args '--nogui'
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenCentral()
    maven {
        name = 'MinecraftForge'
        url = 'https://maven.minecraftforge.net/'
    }
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
    }
}

configurations {
    shade
    implementation.extendsFrom shade
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    shade 'javazoom:jlayer:1.0.1'
    minecraftLibrary 'javazoom:jlayer:1.0.1'
    implementation fg.deobf("maven.modrinth:simple-voice-chat:forge-1.20.1-2.6.22")
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version: forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors: mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    archiveClassifier.set('slim')
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

shadowJar {
    archiveClassifier.set('')
    configurations = [project.configurations.shade]
    relocate 'javazoom', 'com.elestial.jumpscare.shadow.javazoom'
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
    finalizedBy 'reobfShadowJar'
}

reobf {
    shadowJar {}
}

tasks.named('build').configure {
    dependsOn shadowJar
}
