org.gradle.jvmargs=-Xmx1024M
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=elestialjumpscare
mod_name=Elestial Jumpscare Mod
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.elestial.jumpscare
mod_authors=Elestial Team
mod_description=Mod jumpscare player Minecraft 1.20.1 Forge dengan asset gambar dan suara custom yang dapat di-input langsung di game/server, serta mendukung Chat Prefix (!jumpscare <player> <id>) dan command /jumpscare.
